### ISSUE TITLE
setTimeout typo

### ISSUE THREAD

**Issue by WebReflection** [carlosvillu/cv-decorators#1]
You wrote
```
return new Promise( resolve => setTimeout(resolve(`Hi ${name}`), 100) );
```

But I think it should rather be
```
return new Promise( resolve => setTimeout(resolve, 100, `Hi ${name}`) );
```

`setTimeout(invokedCallback())` doesn't invoke that callback later, it does inline, so your example is resolving without any delay (you see it 'cause Promises are async anyway)

Regards

**Comment by carlosvillu** [comment]
Hi,

You're right. It wasn't working as I thought, but I believe it'd be better if I change it for something like this,


```js
return new Promise( resolve => setTimeout(resolve.bind(resolve, `Hi ${name}`), 100) );
```
Now it should do what it's supposed to.


Thanks for the suggestion!

CARLOS

**Comment by WebReflection** [comment]
You are passing the callback itself as bound context which again  doesn't  do what you think it does.

The `resolve` callback doesn't need an execution context, so `null` instead of itself would be way more appropriate.

By standard specifications, `setTimeout` and `setInterval` accept extra arguments, so either you write exactly what I wrote which is just fine and totally cross platform or you drop that bind and use an arrow function  instead.

```js
return new Promise( resolve => setTimeout(() => resolve(`Hi ${name}`), 100) );
```

IMO unnecessary but surely better than what you just wrote.

Regards

**Comment by carlosvillu** [comment]
Hi again,

I didn't know I could pass extra argument to `setTimeout` and it is also cross-browser, so you're absolutely right. I guess you can always learn something new! 

I'll change it right away because it's true that it's more concise this way.

Thanks,
CARLOS
